### ISSUE TITLE
Server Crashed 

### ISSUE THREAD

**Issue by ahoulton** [RTGDaCoder/JDTransfer#1]
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] [15:14:58] [Server thread/WARNING]: Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] [15:14:58] [Server thread/WARNING]: Running PocketMine-MP with 32-bit systems/PHP is deprecated. Support for 32-bit may be dropped in the future.
[Server] [15:14:58] [Server thread/INFO]: Loading pocketmine.yml...
[Server] [15:14:58] [Server thread/INFO]: Loading server properties...
[Server] [15:14:58] [Server thread/INFO]: Selected English (eng) as the base language
[Server] [15:14:58] [Server thread/INFO]: Starting Minecraft: PE server version v1.0.7.0
[Server] [15:14:58] [Server thread/WARNING]: Debugging assertions are enabled, this may impact on performance. To disable them, set `zend.assertions = -1` in php.ini.
[Server] [15:14:58] [Server thread/INFO]: Opening server on 0.0.0.0:41068
[Server] [15:14:58] [Server thread/INFO]: This server is running PocketMine-MP version 1.6.2dev-76 "Unleashed" (API 3.0.0-ALPHA5)
[Server] [15:14:58] [Server thread/INFO]: PocketMine-MP is distributed under the LGPL License
[Server] [15:14:59] [Server thread/INFO]: Loading recipes...
[Server] [15:15:00] [Server thread/INFO]: Loading resource packs...
[Server] [15:15:00] [Server thread/INFO]: Loading PurePerms v1.4.0-INDEV
[Server] [15:15:00] [Server thread/NOTICE]: PurePerms by 64FF00 & ProjectInfinity! #LEET.CC
[Server] 
[Server] 888 888 .d8888b. d8888 8888888888 8888888888 .d8888b. .d8888b. 
[Server] 888 888 d88P Y88b d8P888 888 888 d88P Y88b d88P Y88b
[Server] 888888888888 888 d8P 888 888 888 888 888 888 888
[Server] 888 888 888d888b. d8P 888 8888888 8888888 888 888 888 888
[Server] 888 888 888P "Y88b d88 888 888 888 888 888 888 888
[Server] 888888888888 888 888 8888888888 888 888 888 888 888 888
[Server] 888 888 Y88b d88P 888 888 888 Y88b d88P Y88b d88P
[Server] 888 888 "Y8888P" 888 888 888 "Y8888P" "Y8888P" 
[Server] 
[Server] [15:15:01] [Server thread/INFO]: [PurePerms] Setting default language to 'en'
[Server] [15:15:01] [Server thread/NOTICE]: [PurePerms] Multiworld support is currently disabled.
[Server] [15:15:01] [Server thread/NOTICE]: [PurePerms] Don't forget to set enable-multiworld-perms option in config.yml to true if you want to use per-world permissions!
[Server] [15:15:01] [Server thread/INFO]: Loading DevTools v1.11.3
[Server] [15:15:01] [Server thread/INFO]: Loading PureChat v1.4.1
[Server] [15:15:01] [Server thread/INFO]: Enabling DevTools v1.11.3
[Server] [15:15:01] [Server thread/INFO]: Loading source plugin JDTransfer v1.1.1
[Server] [15:15:01] [Server thread/INFO]: [DevTools] Registered folder plugin loader
[Server] [15:15:01] [Server thread/INFO]: Preparing level "world"
[Server] [15:15:01] [Server thread/INFO]: Enabling PurePerms v1.4.0-INDEV
[Server] [15:15:01] [Server thread/NOTICE]: [PurePerms] Set data provider to YAMLv1.
[Server] [15:15:01] [Server thread/INFO]: Enabling PureChat v1.4.1
[Server] [15:15:01] [Server thread/NOTICE]: [PureChat] No valid factions plugin in default-factions-plugin node was found. Disabling factions plugin support.
[Server] [15:15:01] [Server thread/INFO]: Enabling JDTransfer v1.1.1
[Server] [15:15:02] [Server thread/INFO]: Starting GS4 status listener
[Server] [15:15:02] [Server thread/INFO]: Setting query port to 41068
[Server] [15:15:02] [Server thread/INFO]: Query running on 0.0.0.0:41068
[Server] [15:15:02] [Server thread/INFO]: Default game type: Survival Mode
[Server] [15:15:02] [Server thread/INFO]: Done (9.908s)! For help, type "help" or "?"
>jdt
>jdt
>
[Server] [15:16:04] [Server thread/INFO]: HoultonGames[/127.0.0.1:19132] logged in with entity id 1 at (world, 500, 58, -99)
[Server] [15:16:04] [Server thread/INFO]: There are 1/5 players online:
[Server] [15:16:04] [Server thread/INFO]: HoultonGames
[Server] [15:16:06] [Server thread/INFO]: HoultonGames joined the game
[PocketMine] Server was stopped.
(When /jdt is run by player)

**Comment by InspectorGadget** [comment]
Yes, i'm aware of this. Please wait till i push an update out. I'm already working on an update.
